apiVersion: v1
kind: Service
metadata:
  name: webserver
spec:
  type: ClusterIP
  selector:
    app: webserver
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      name: nginx
      labels:
        app: webserver
    spec:
      containers:
        - name: nginx
          image: docker.io/nginx:latest
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: 128Mi
              cpu: 0.5
            requests:
              memory: 64Mi
              cpu: 0.3

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      name: httpd
      labels:
        app: webserver
    spec:
      containers:
        - name: httpd
          image: docker.io/httpd:latest
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: 128Mi
              cpu: 0.5
            requests:
              memory: 64Mi
              cpu: 0.3
