apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: ClusterIP
  selector:
    app: webserver
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80 
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      name: nginx
      labels:
        app: webserver
    spec:
      containers:
        - name: nginx
          image: docker.io/nginx:latest
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              memory: 64Mi
              cpu: 0.3
            requests:
              memory: 32Mi
              cpu: 0.1
